networks:
    blazorapp:
        external: true
   

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrongPassword123!", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 10
    container_name: blazor-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  blazorinvoiceapp:
    build:
      context: .
      dockerfile: BlazorInvoiceApp/Dockerfile
    container_name: blazor-app
    ports:
      - "8001:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - DEMO_EMAIL=demo@test.com
      - DEMO_PASSWORD=Demo123!
  

volumes:
  sql_data:
  
